apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-flask-app
  labels:
    app: pre-production-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre-production-flask-app
  template:
    metadata:
      labels:
        app: pre-production-flask-app
    spec:
      containers:
      - name: flask-app
        image: mahaamin97/pre-production-flask-app
        ports:
        - containerPort: 5000